# 配置服务端口号
server:
  port: 8501

# 配置数据库连接信息
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_spzx
    username: root
    password: 123456
  # Redis的相关配置
  data:
    redis:
      host: localhost
      port: 6379
#  password: 1234

# mybatis的配置
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*/*.xml

#过滤器放行内容
spzx:
  auth:
    noAuthUrls:
      - /admin/system/index/login
      - /admin/system/index/generateValidateCode
      - /doc.html
      - /webjars/**
      - /favicon.ico
      - /v3/**
  minio:
    endpointUrl: http://127.0.0.1:9000
    accessKey: Qxj6SqNo6LlOQ0ctPnnV
    secreKey: zvxUyFYzryql0FGQ3HC1MzK953i2Z0Co6t6BitAb
    bucketName: spzx-bucket